name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - phase6-admin-features
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - phase6-admin-features

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: e6cf1b2943ad5bdad9013e7f40dc60e2d2a3a08c4e11919f1919d09c3531e0e606-7a9218da-034d-48d8-a6f7-93682c6c0cc000f09070bd76be0f
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./WebApplication4/bookstore-client" # App source code path
          api_location: "./WebApplication4" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: e6cf1b2943ad5bdad9013e7f40dc60e2d2a3a08c4e11919f1919d09c3531e0e606-7a9218da-034d-48d8-a6f7-93682c6c0cc000f09070bd76be0f
          action: "close"
