name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - phase6-admin-features
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - phase6-admin-features

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      # Build the React app and copy the build output to a new directory
      - name: Build React App
        run: |
          cd WebApplication4/bookstore-client
          # Set CI=false to prevent treating warnings as errors
          export CI=false
          npm ci
          npm run build
          # Create a new directory for the static web app
          mkdir -p ../../static-web-app
          # Copy the build output to the new directory
          cp -r build/* ../../static-web-app/
          # Double-check that configuration files are in the new directory
          cp -f public/routes.json ../../static-web-app/
          cp -f public/staticwebapp.config.json ../../static-web-app/
          echo "Contents of static-web-app directory:"
          ls -la ../../static-web-app
          
      # Note: This deployment only includes the frontend React app.
      # The ASP.NET Core API needs to be deployed separately to an Azure App Service
      # or converted to Azure Functions to work with Azure Static Web Apps.
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: "d176ac05541ec42b80826ff11ed9f669d30381bdb5a30b60be3860f7db0f509a06-44edb073-b90d-425c-b1c4-66e796ef5d4300f09070bd76be0f"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "static-web-app"
          api_location: ""
          output_location: ""
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: "d176ac05541ec42b80826ff11ed9f669d30381bdb5a30b60be3860f7db0f509a06-44edb073-b90d-425c-b1c4-66e796ef5d4300f09070bd76be0f"
          action: "close"
